DROP TABLE USERS;

CREATE TABLE USERS (
FIRSTNAME  VARCHAR2(15) ,
LASTNAME VARCHAR2(15) ,
EMAIL VARCHAR2(50),
BIRTHDAY VARCHAR2(50) ,
TITLE VARCHAR2(10),
USERNAME VARCHAR2(15) PRIMARY KEY,
PASSWORD VARCHAR2(15)
);

DROP TABLE ITEMS;
CREATE TABLE ITEMS (
NAME VARCHAR2(50) NOT NULL,
S_N VARCHAR2(20) , 
CATEGORY VARCHAR2(50) NOT NULL, 
ANCILLARY_ITEMS VARCHAR2(100),
AMOUNT NUMBER DEFAULT 1,
STATUS VARCHAR2(20) DEFAULT 'IN' NOT NULL,
PRECAUTIONS VARCHAR2(100),
BORROW_DATE VARCHAR2(50),
RETURN_DATE VARCHAR2(50), 
PRIMARY KEY(NAME, S_N)
);
