DROP TABLE USERS;

CREATE TABLE USERS (
FIRSTNAME  VARCHAR2(15) ,
LASTNAME VARCHAR2(15) ,
EMAIL VARCHAR2(50),
BIRTHDAY VARCHAR2(50) ,
TITLE VARCHAR2(10),
USERNAME VARCHAR2(15) PRIMARY KEY,
PASSWORD VARCHAR2(15)
);

