pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    docker.withRegistry('Jenkins/Dockerfile.unknown', 'docker-registry-credentials') {
                        def app = docker.build("Jenkins/Dockerfile.unknown/your-image-name:${env.BUILD_NUMBER}")
                        app.push()
                    }
                }
            }
        }
    }
}