pipeline {
    agent {
        docker {
            image 'node:14'
            args '-u root'
        }
    }
    
    environment {
        DOCKER_REGISTRY = 'your-docker-registry.com'
        DOCKER_REGISTRY_CREDENTIALS = credentials('docker-registry-credentials')
        DOCKER_IMAGE_NAME = 'your-image-name'
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    docker.withRegistry(DOCKER_REGISTRY, DOCKER_REGISTRY_CREDENTIALS) {
                        def app = docker.build("${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:${env.BUILD_NUMBER}")
                        app.push()
                    }
                }
            }
        }
    }
}