pipeline {
  agent any
  environment {
    DOCKER_COMPOSE_VERSION = '1.29.2'
  }
  stages {
    stage('Build Docker Images') {
      steps {
        script {
          docker.build('client', './client')
          docker.build('server', './server')
        }
      }
    }
    stage('Run Docker Containers with Docker Compose') {
      steps {
        sh 'curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose'
        sh 'chmod +x docker-compose'
        sh './docker-compose up -d'
      }
    }
    stage('Stop Docker Containers with Docker Compose') {
      steps {
        sh './docker-compose down'
      }
    }
  }
  post {
    always {
      sh 'docker images -q | xargs docker rmi -f || true'
    }
  }
}